all:
	make play_again1
	make play_again2
	make play_again3
	make play_again4
	make sigdemo1
	make sigdemo2
all_debug:
	make play_again1_d
	make play_again2_d
	make play_again3_d
	make play_again4_d
	make sigdemo1_d
	make sigdemo2_d

play_again1:
	gcc -O2 -Wextra -Wall -Werror -o play_again1 play_again1.c
play_again1_d:
	gcc -Wextra -Wall -Werror -o play_again1_d play_again1.c

play_again2:
	gcc -O2 -Wextra -Wall -Werror -o play_again2 play_again2.c
play_again2_d:
	gcc -Wextra -Wall -Werror -o play_again2_d play_again2.c

play_again3:
	gcc -O2 -Wextra -Wall -Werror -o play_again3 play_again3.c
play_again3_d:
	gcc -Wextra -Wall -Werror -o play_again3_d play_again3.c

play_again4:
	gcc -O2 -Wextra -Wall -Werror -o play_again4 play_again4.c
play_again4_d:
	gcc -Wextra -Wall -Werror -o play_again4_d play_again4.c

sigdemo1:
	gcc -O2 -Wextra -Wall -Werror -o sigdemo1 sigdemo1.c
sigdemo1_d:
	gcc -Wextra -Wall -Werror -o sigdemo1_d sigdemo1.c

sigdemo2:
	gcc -O2 -Wextra -Wall -Werror -o sigdemo2 sigdemo2.c
sigdemo2_d:
	gcc -Wextra -Wall -Werror -o sigdemo2_d sigdemo2.c
